---
title: "Trabajo encuesta guacheras"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup global del informe, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      messages = FALSE)
```

```{r paquetes}
pacman::p_load(tidyverse, janitor,  skimr, rio, here,
               GGally, correlation, performance, scales, 
               emmeans, multcomp, oddsratio, coefplot,
               OddsPlotty, finalfit, relaimpo, gtools, SjPlot)
pacman::p_load(rpart, rpart.plot)
pacman::p_load(sjPlot)
conflicted::conflict_prefer("select", "dplyr")
conflicted::conflict_prefer("filter", "dplyr")
```

## Datos

```{r}
dat <- import(here::here("survey/survey23.csv"))
# str(dat)
dat %>% skim() 
```


### Exploración 

```{r}
dat %>% 
  pivot_longer(cols = -c(SCC, Milk_yield, Fertility_first_insemination, Mortality, Age_first_service)) %>% 
  group_by(name,value) %>% 
  count() %>% 
  group_by(name) %>% 
  mutate(
    prop = n/sum(n, na.rm=TRUE), 
    perc = scales::percent(prop) ,
    value= factor(value)) %>% 
  ggplot(aes(x=name, y=prop, fill=fct_rev(value)), col="grey70") +
  geom_bar(stat="identity") + 
  geom_text(aes(label = value),
            position = position_stack(vjust = 0.5), size = 2) +
  scale_y_continuous(name="", labels = percent) +
  coord_flip() + 
  guides(fill="none")
```

```{r}
dat %>% 
  pivot_longer(cols = c(SCC, Milk_yield, Fertility_first_insemination, Mortality)) %>% 
  ggplot(aes(x=value)) +
  geom_histogram() + 
  ggstance::geom_boxploth(aes(y = 3), width = 2, color = "blue", lwd = 2, alpha = .5) +
  facet_wrap("name", scales="free")  
```
```{r}
ggsave(last_plot(), file="survey/histogramas.tiff", 
       w=150, h=100, units="mm", dpi=300)
```
##Milking cows
```{r}
encuesta_original <- read_csv("survey/encuesta_original.csv")

str(encuesta_original) 
```

```{r}
encuesta_original$P21<-as.numeric(encuesta_original$P21)
```

```{r}
hist(encuesta_original$P21,  freq=TRUE,
     main='Histogram for Milking cows',
     xlab='Milking cows',
     ylab='Frecuencia')
```



```{r}
encuesta_original %>% 
  pivot_longer(cols = c(P21)) %>% 
  ggplot(aes(x=value)) +
  geom_histogram() + 
  ggstance::geom_boxploth(aes(y = 3), width = 2, color = "blue", lwd = 2, alpha = .5) +
  facet_wrap("name", scales="free")
  
```
```{r}
str(encuesta_original$P21)
mean(encuesta_original$P21, na.rm=TRUE)
```
```{r}
res <- t.test(x=encuesta_original$P21, conf.level=0.95)
res$conf.int
```
```{r}
summary(encuesta_original$P21)
```

```{r}
encuesta_original$P26<-as.numeric(encuesta_original$P26)
```

```{r}
hist(encuesta_original$P26,  freq=TRUE,
     main='Histogram for Fat in milk, %',
     xlab='Fat, %',
     ylab='Frecuencia')
```



```{r}
encuesta_original %>% 
  pivot_longer(cols = c(P26)) %>% 
  ggplot(aes(x=value)) +
  geom_histogram() + 
  ggstance::geom_boxploth(aes(y = 3), width = 2, color = "blue", lwd = 2, alpha = .5) +
  facet_wrap("name", scales="free")
  
```
```{r}
str(encuesta_original$P26)
mean(encuesta_original$P26, na.rm=TRUE)
```
```{r}
res <- t.test(x=encuesta_original$P26, conf.level=0.95)
res$conf.int
```
```{r}
summary(encuesta_original$P26)
```
```{r}
encuesta_original$P27<-as.numeric(encuesta_original$P27)
```

```{r}
hist(encuesta_original$P27,  freq=TRUE,
     main='Histogram for Protein in milk, %',
     xlab='Protein, %',
     ylab='Frecuencia')
```



```{r}
encuesta_original %>% 
  pivot_longer(cols = c(P27)) %>% 
  ggplot(aes(x=value)) +
  geom_histogram() + 
  ggstance::geom_boxploth(aes(y = 3), width = 2, color = "blue", lwd = 2, alpha = .5) +
  facet_wrap("name", scales="free")
  
```
```{r}
str(encuesta_original$P27)
mean(encuesta_original$P27, na.rm=TRUE)
```
```{r}
res <- t.test(x=encuesta_original$P27, conf.level=0.95)
res$conf.int
```
```{r}
summary(encuesta_original$P27)
```

```{r}
encuesta_original$P32<-as.numeric(encuesta_original$P32)
```

```{r}
hist(encuesta_original$P32,  freq=TRUE,
     main='Histogram for Age at first calving',
     xlab='Age at first calving',
     ylab='Frecuencia')
```



```{r}
encuesta_original %>% 
  pivot_longer(cols = c(P32)) %>% 
  ggplot(aes(x=value)) +
  geom_histogram() + 
  ggstance::geom_boxploth(aes(y = 3), width = 2, color = "blue", lwd = 2, alpha = .5) +
  facet_wrap("name", scales="free")
  
```
```{r}
str(encuesta_original$P32)
mean(encuesta_original$P32, na.rm=TRUE)
```
```{r}
res <- t.test(x=encuesta_original$P32, conf.level=0.95)
res$conf.int
```
```{r}
summary(encuesta_original$P32)
```
```{r}
encuesta_original$P33<-as.numeric(encuesta_original$P33)
```

```{r}
hist(encuesta_original$P33,  freq=TRUE,
     main='Histogram for Open days',
     xlab='Open days',
     ylab='Frecuencia')
```



```{r}
encuesta_original %>% 
  pivot_longer(cols = c(P33)) %>% 
  ggplot(aes(x=value)) +
  geom_histogram() + 
  ggstance::geom_boxploth(aes(y = 3), width = 2, color = "blue", lwd = 2, alpha = .5) +
  facet_wrap("name", scales="free")
  
```
```{r}
str(encuesta_original$P33)
mean(encuesta_original$P33, na.rm=TRUE)
```
```{r}
res <- t.test(x=encuesta_original$P33, conf.level=0.95)
res$conf.int
```
```{r}
summary(encuesta_original$P33)
```
```{r}
encuesta_original$P34<-as.numeric(encuesta_original$P34)
```

```{r}
hist(encuesta_original$P34,  freq=TRUE,
     main='Histogram for Calving interval',
     xlab='Calving interval',
     ylab='Frecuencia')
```



```{r}
encuesta_original %>% 
  pivot_longer(cols = c(P34)) %>% 
  ggplot(aes(x=value)) +
  geom_histogram() + 
  ggstance::geom_boxploth(aes(y = 3), width = 2, color = "blue", lwd = 2, alpha = .5) +
  facet_wrap("name", scales="free")
  
```
```{r}
str(encuesta_original$P34)
mean(encuesta_original$P34, na.rm=TRUE)
```
```{r}
res <- t.test(x=encuesta_original$P34, conf.level=0.95)
res$conf.int
```
```{r}
summary(encuesta_original$P34)
```
```{r}
encuesta_original$P35<-as.numeric(encuesta_original$P35)
```

```{r}
hist(encuesta_original$P35,  freq=TRUE,
     main='Histogram for Body condition score at calving',
     xlab='Body condition score at calving',
     ylab='Frecuencia')
```



```{r}
encuesta_original %>% 
  pivot_longer(cols = c(P35)) %>% 
  ggplot(aes(x=value)) +
  geom_histogram() + 
  ggstance::geom_boxploth(aes(y = 3), width = 2, color = "blue", lwd = 2, alpha = .5) +
  facet_wrap("name", scales="free")
  
```
```{r}
str(encuesta_original$P35)
mean(encuesta_original$P35, na.rm=TRUE)
```
```{r}
res <- t.test(x=encuesta_original$P35, conf.level=0.95)
res$conf.int
```
```{r}
summary(encuesta_original$P32)
```

```{r}
encuesta_original$P36<-as.numeric(encuesta_original$P36)
```

```{r}
hist(encuesta_original$P36,  freq=TRUE,
     main='Histogram for Dystocic calvings in cows',
     xlab='Dystocic calvings in cows',
     ylab='Frecuencia')
```



```{r}
encuesta_original %>% 
  pivot_longer(cols = c(P36)) %>% 
  ggplot(aes(x=value)) +
  geom_histogram() + 
  ggstance::geom_boxploth(aes(y = 3), width = 2, color = "blue", lwd = 2, alpha = .5) +
  facet_wrap("name", scales="free")
  
```
```{r}
str(encuesta_original$P36)
mean(encuesta_original$P36, na.rm=TRUE)
```
```{r}
res <- t.test(x=encuesta_original$P36, conf.level=0.95)
res$conf.int
```
```{r}
summary(encuesta_original$P36)
```

```{r}
encuesta_original$P37<-as.numeric(encuesta_original$P37)
```

```{r}
hist(encuesta_original$P37,  freq=TRUE,
     main='Histogram for Discard for infertility',
     xlab='Discard for infertility',
     ylab='Frecuencia')
```



```{r}
encuesta_original %>% 
  pivot_longer(cols = c(P37)) %>% 
  ggplot(aes(x=value)) +
  geom_histogram() + 
  ggstance::geom_boxploth(aes(y = 3), width = 2, color = "blue", lwd = 2, alpha = .5) +
  facet_wrap("name", scales="free")
  
```
```{r}
str(encuesta_original$P37)
mean(encuesta_original$P37, na.rm=TRUE)
```
```{r}
res <- t.test(x=encuesta_original$P37, conf.level=0.95)
res$conf.int
```
```{r}
summary(encuesta_original$P37)
```
```{r}
encuesta_original$P38<-as.numeric(encuesta_original$P38)
```

```{r}
hist(encuesta_original$P38,  freq=TRUE,
     main='Histogram for Rest period',
     xlab='Rest period, days',
     ylab='Frecuencia')
```



```{r}
encuesta_original %>% 
  pivot_longer(cols = c(P38)) %>% 
  ggplot(aes(x=value)) +
  geom_histogram() + 
  ggstance::geom_boxploth(aes(y = 3), width = 2, color = "blue", lwd = 2, alpha = .5) +
  facet_wrap("name", scales="free")
  
```
```{r}
str(encuesta_original$P38)
mean(encuesta_original$P38, na.rm=TRUE)
```
```{r}
res <- t.test(x=encuesta_original$P38, conf.level=0.95)
res$conf.int
```
```{r}
summary(encuesta_original$P38)
```

```{r}
encuesta_original$P39<-as.numeric(encuesta_original$P39)
```

```{r}
hist(encuesta_original$P39,  freq=TRUE,
     main='Histogram for Mortality rate in cows',
     xlab='Mortality rate in cows',
     ylab='Frecuencia')
```



```{r}
encuesta_original %>% 
  pivot_longer(cols = c(P39)) %>% 
  ggplot(aes(x=value)) +
  geom_histogram() + 
  ggstance::geom_boxploth(aes(y = 3), width = 2, color = "blue", lwd = 2, alpha = .5) +
  facet_wrap("name", scales="free")
  
```
```{r}
str(encuesta_original$P39)
mean(encuesta_original$P39, na.rm=TRUE)
```
```{r}
res <- t.test(x=encuesta_original$P39, conf.level=0.95)
res$conf.int
```
```{r}
summary(encuesta_original$P39)
```

```{r}
encuesta_original$P24<-as.numeric(encuesta_original$P24)
```

```{r}
hist(encuesta_original$P24,  freq=TRUE,
     main='Histogram for Milk yield',
     xlab='Milk yield',
     ylab='Frecuencia')
```

```{r}
encuesta_original %>% 
  pivot_longer(cols = c(P24)) %>% 
  ggplot(aes(x=value)) +
  geom_histogram() + 
  ggstance::geom_boxploth(aes(y = 3), width = 2, color = "blue", lwd = 2, alpha = .5) +
  facet_wrap("name", scales="free")
  
```
```{r}
str(encuesta_original$P24)
mean(encuesta_original$P24, na.rm=TRUE)
```
```{r}
res <- t.test(x=encuesta_original$P24, conf.level=0.95)
res$conf.int
```
```{r}
summary(encuesta_original$P24)
```
```{r}
encuesta_original$P25<-as.numeric(encuesta_original$P25)
```

```{r}
hist(encuesta_original$P25,  freq=TRUE,
     main='Histogram for SCC',
     xlab='Somatic count cells',
     ylab='Frecuencia')
```



```{r}
encuesta_original %>% 
  pivot_longer(cols = c(P25)) %>% 
  ggplot(aes(x=value)) +
  geom_histogram() + 
  ggstance::geom_boxploth(aes(y = 3), width = 2, color = "blue", lwd = 2, alpha = .5) +
  facet_wrap("name", scales="free")
  
```
```{r}
str(encuesta_original$P25)
mean(encuesta_original$P25, na.rm=TRUE)
```
```{r}
res <- t.test(x=encuesta_original$P25, conf.level=0.95)
res$conf.int
```
```{r}
encuesta_original$P29<-as.numeric(encuesta_original$P29)
```

```{r}
str(encuesta_original$P29)
mean(encuesta_original$P29, na.rm=TRUE)
```
```{r}
res <- t.test(x=encuesta_original$P29, conf.level=0.95)
res$conf.int
```

```{r}
encuesta_original$P31<-as.numeric(encuesta_original$P31)
```

```{r}
str(encuesta_original$P31)
mean(encuesta_original$P31, na.rm=TRUE)
```
```{r}
res <- t.test(x=encuesta_original$P31, conf.level=0.95)
res$conf.int
```




```{r}
str(dat$prepartum)
new<-dat %>% 
  mutate(as.factor(prepartum))
new

str(new)
```

```{r}
Prepartum<-table(new$`as.factor(prepartum)`)
```
```{r}
library(sjmisc) # Utilidades para encuestas con etiquetas
library(survey) # Análisis de encuestas complejas
library(car)    # Inferencia de modelos
```


```{r}
porcentajes <- prop.table(Prepartum)                     #F) Calcular frecuencias relativas
porcentaje <- as.data.frame(Prepartum); porcentaje   #G) Convertir a data frame
```
```{r}
dat %>% frq(prepartum,weights=peso,sort.frq="desc") %>% kable()
```









